---
title: "Introduction to wcr"
author: "Kazuki Yoshida"
date: "2016-04-22"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to wcr}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, message = FALSE, tidy = FALSE, echo = F}
## Create a header using devtools::use_vignette("my-vignette")
## knitr configuration: http://yihui.name/knitr/options#chunk_options
library(knitr)
showMessage <- FALSE
showWarning <- TRUE
set_alias(w = "fig.width", h = "fig.height", res = "results")
opts_chunk$set(comment = "", error= TRUE, warning = showWarning, message = showMessage,
               tidy = FALSE, cache = F, echo = T,
               fig.width = 7, fig.height = 7, dev.args = list(family = "sans"))

## R configuration
options(width = 116, scipen = 5)
```

## What is wcr?

The wcr package is an R package that implements within-cluster resampling (a.k.a. multiple outputation).


## Load packages

```{r}
## wcrpackage itself
## library(wcr)
```
```

--------------------
- Authored by Kazuki Yoshida
- github page: https://github.com/kaz-yos/wcr
